version: '3.2'

services:

  atomictime:
    build: ./
    container_name: rintoexa-atomictime
    ports:
      - "127.0.0.1:23000:80"
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
